<main>

    <form id="storyForm" method='get' action="">

    <fieldset>

    <h2>
        <?= $story ?>
    </h2>

        <?php require "templates/partials/choices/name.phtml"?>
    
    <button type="submit">Valider</button>
    </fieldset>

    </form>

    <!-- <script>
        const form = document.getElementById('storyForm');
        const select = document.getElementById('storyChoice');

        form.addEventListener('submit', function() {
            select.disabled = true; // empêche toute modification
        });
    </script> -->
</main>