<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>L'histoire dont vous êtes le héro</title>

        <!-- CSS non utilisé (copier-coller d'un exercice) -->
        <!-- <link rel="stylesheet" href="assets/styles/style.css"> -->
    </head>
    <body>
        <?php require "templates/partials/_header.phtml"?>
        <?php require "templates/partials/_main.phtml"?>
        <?php require "templates/partials/_footer.phtml"?>
    </body>
</html>