<label for="storyChoice">
        <?php require "controllers/paths.php"?>
        <h5>
            <?= $pageContent[$path_number]?>
        </h5>
</label>

<select name="name" id="storyChoice">
    <?php foreach($paths[$path_number] as $value => $choice){ ?>

        <option value="<?= $value?>">
           <?= $choice ?>
        </option>
    <?php }?>

</select>

<?php
if (isset($_GET["name"])){

    if($_GET["name"]==='1'){
	    require "templates/partials/choices/choice1.phtml";
    }
        
    else if($_GET["name"]==='2'){
	    require "templates/partials/choices/choice2.phtml";
    }
         
    else if($_GET["name"]==='3'){
	    require "templates/partials/choices/choice3.phtml";
    }
}
?>